export interface Product {
 category: null,
    categoryId: number,
    description: string,
    name: string,
    orderDetails: null,
    price: number,
    productId: number,
    productInventory: null,
    seller: null,
    sellerId: number,
    stock: number,
    mainImage: string,
    secondImage: string,
    thirdImage: string,
    Details: string,
};
