export interface Product {
 category: null,
    categoryId: number,
    description: string,
    name: string,
    orderDetails: null,
    price: number,
    productId: number,
    productInventory: null,
    seller: null,
    sellerId: number,
    stock: number,
    MainImage: string,
    SecondImage: string,
    ThirdImage: string,
    Details: string,
};
